name: Cypress-CI

on:
  pull_request:
    branches: [develop]
  workflow_dispatch:

jobs:
  cypress_run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          install-command: yarn --frozen-lockfile --silent
          build: yarn build
          start: yarn start
          wait-on: http://localhost:3000
