name: Development CI & Unit Testing

on:
  pull_request:
    branches: [develop]
  workflow_dispatch:

jobs:
  cypress_run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
        with:
          install-command: yarn --frozen-lockfile --silent
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: yarn dev
          wait-on: http://localhost:3000
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
        with:
          install-command: yarn --frozen-lockfile --silent
      - name: Run tests
        run: yarn test
