name: Cypress-CI

on:
  pull_request:
    branches: [develop]
  workflow_dispatch:

jobs:
  cypress_run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          install-command: yarn --frozen-lockfile --silent
          build: yarn build
          start: yarn start
          wait-on: http://localhost:3000
